typography_spectrum: 0.6337162649724633
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8514747312292457
  lightness: 0.19552486832253635
  saturation: 0.2951384470798075
  rhythmicContrast: 0.3468236669432372
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03729587933048606
analytics:
  google: null
  facebook: null
  twitter: null
name: domshov
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Dom Shovelton '
purpose: []
